name: "Changed Files Labeler"
description: "Add labels based on the paths of modified files"
author: "maxisam"
branding:
  icon: tag
  color: red
inputs:
  authToken:
    description: The GitHub token
    required: true
  prNumber:
    description: The pull request number
    default: ${{ github.event.pull_request.number || github.event.number }}
    required: false
  basePaths:
    description: The base path to match like path1|path2
    required: true
  prefixes:
    description: Prefix to be used in label, like prefix1|prefix2 for 2 layers, prefix can also used for skipping label by setting it as skip and set "" will use the original label
    required: false
  delimiter:
    description: Delimiter between prefix and label(e.g., space)
    default: ":"
    required: false
  includedGlob:
    description: The file extensions to include to check for changed files
    default: "**/*.{js,ts,jsx,tsx,go,py,java,swift,php,rb,cs,sh}"
    required: false
  layers:
    description: The number of layers to use for the label
    default: 1
    required: false
  debugShowPaths:
    description: Show all PR paths in debug mode
    default: false
    required: false
  skipLabels:
    description: Don't push labels to github
    default: false
    required: false
outputs:
  changed:
    description: all changed files
  paths:
    description: The unique paths of modified files
  labels:
    description: The labels to add to the pull request
runs:
  using: "node20"
  main: "dist/index.js"
